### ISSUE TITLE
subtraction underflow throws sum error

### ISSUE THREAD

**Issue by wanseob** [Zokrates/pycrypto#7] opened 2019-08-12 16:04 UTC
I was testing simple homomorphic feature but I it suceeded some times. 
The bug seems because of the subtraction of the field elements is broken when underflow occurs.

Here is the code to reproduce the situation. 
```python
from zokrates_pycrypto.field import FQ
from zokrates_pycrypto.babyjubjub import Point

G = Point.from_y(FQ(20819045374670962167435360035096875258406992893633759881276124905556507972311))

def test_sub_hh():
    a = FQ(30)
    b = FQ(5)
    print("G*(a-b):  ", G*(a-b))
    print("G*a-G*b: ", G*a-G*b)
    print("G*(a-b) == G*a-G*b : ", G*a-G*b == G*(a-b)) # returns True

    print("G*(b-a):   ", G*(b-a))
    print("G*b-G*a): ", G*b-G*a)
    print("G*(b-a) == G*b-G*a : ", G*b-G*a == G*(b-a)) # returns False
if __name__ == "__main__":
    test_sub_hh()
```

**Comment by wanseob** [comment] 2019-08-13 07:14
Another test result. Using subtraction instead of addition when an overflow occurs is fixing the problem.
```python
from zokrates_pycrypto.field import FQ
from zokrates_pycrypto.babyjubjub import Point

G = Point.from_y(FQ(20819045374670962167435360035096875258406992893633759881276124905556507972311))

def test_sub_hh():
    a = FQ(30)
    # b = FQ(-5)
    b = FQ(21888242871839275222246405745257275088548364400416034343698204186575808495612) 
    c = -b # FQ(5)

    print("G*(a+b):      ", G*(a+b))   # x: 902..., y:328...
    print("G*(a) - G(c): ", G*a - G*c) # x: 902..., y:328...
    print("G*(a) + G(b): ", G*a + G*b) # x: 129..., y:184...

if __name__ == "__main__":
    test_sub_hh()
```

**Comment by wanseob** [comment] 2019-08-15 15:55
It was because `(a+b)` should be added in the Fr field which modulus is 21888242871839275222246405745257275088614511777268538073601725287587578984328

**Comment by wanseob** [comment] 2019-08-18 09:26
Please refer this PR :)
https://github.com/HarryR/ethsnarks/pull/154

**Comment by stefandeml** [comment] 2019-08-22 21:53
Thanks, I will add this shortly.

**Comment by stefandeml** [comment] 2019-09-30 14:49
As @wanseob pointed out the problem is not the current `FQ` implementation, but the fact that in the example the computation is done over the order of the curve.

Currently the `field.py` is a direct copy of the work in `py_ecc`.
Making the modulus generic would break this. I will close this issue for now and we could think about creating another issue for making `field.py` generic.

**Closed as completed by stefandeml** 2019-09-30 14:49 UTC
